# Generated by Django 4.2.5 on 2023-10-24 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GestionSoutien', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QCM',
            fields=[
                ('id_qcm', models.AutoField(primary_key=True, serialize=False)),
                ('nom_qcm', models.CharField(max_length=50)),
                ('id_matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionSoutien.matiere')),
                ('id_semaine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionSoutien.semaine')),
            ],
            options={
                'db_table': 'qcm',
            },
        ),
        migrations.CreateModel(
            name='ResultatQCM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField()),
                ('id_qcm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QCM.qcm')),
                ('num_etu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionSoutien.eleve')),
            ],
            options={
                'db_table': 'resultatqcm',
            },
        ),
    ]
