# Generated by Django 4.2.5 on 2023-10-24 13:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionSoutien', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creneau',
            name='heure_debut',
            field=models.TimeField(validators=[django.core.validators.MaxValueValidator('18:00'), django.core.validators.MinValueValidator('08:00')]),
        ),
        migrations.AlterField(
            model_name='creneau',
            name='jour',
            field=models.IntegerField(default=2, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='periode',
            name='date_debut',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='periode',
            name='date_fin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='semaine',
            name='date_debut',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='semaine',
            name='date_fin',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='creneau',
            unique_together={('jour', 'heure_debut')},
        ),
    ]
