# Generated by Django 4.2.5 on 2023-10-27 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionSoutien', '0002_alter_creneau_heure_debut_alter_creneau_jour_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='matiere',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='matiere',
            name='id_periode',
        ),
    ]
