# Generated by Django 3.2.12 on 2024-02-05 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionSoutien', '0004_professeur_mdp_provisoire_prof'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soutien',
            fields=[
                ('id_soutien', models.AutoField(primary_key=True, serialize=False)),
                ('id_creneau', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionSoutien.creneau')),
                ('id_matiere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionSoutien.matiere')),
                ('id_semaine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionSoutien.semaine')),
            ],
            options={
                'db_table': 'soutien',
            },
        ),
        migrations.CreateModel(
            name='ParticiperSoutienProfesseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disponibilite', models.BooleanField(default=False)),
                ('organise', models.BooleanField(default=False)),
                ('id_soutien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionSoutien.soutien')),
                ('num_prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionSoutien.professeur')),
            ],
            options={
                'db_table': 'participersoutienprofesseur',
            },
        ),
        migrations.CreateModel(
            name='ParticiperSoutienEleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire', models.CharField(max_length=800)),
                ('id_soutien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionSoutien.soutien')),
                ('num_etu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionSoutien.eleve')),
            ],
            options={
                'db_table': 'participersoutieneleve',
            },
        ),
    ]
