# Generated by Django 4.2.5 on 2023-10-24 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GestionSoutien', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sondage',
            fields=[
                ('id_sond', models.AutoField(primary_key=True, serialize=False)),
                ('id_semaine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionSoutien.semaine')),
            ],
            options={
                'db_table': 'sondage',
            },
        ),
        migrations.CreateModel(
            name='RepSondage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matiere_voulue', models.CharField(max_length=100)),
                ('volontaire', models.CharField(max_length=50)),
                ('commentaire', models.CharField(max_length=800)),
                ('id_sondage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sondages.sondage')),
                ('num_etu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionSoutien.eleve')),
            ],
            options={
                'db_table': 'repsondage',
            },
        ),
    ]
