# Generated by Django 4.2.5 on 2023-10-24 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GestionSoutien', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParamDef',
            fields=[
                ('id_param', models.AutoField(primary_key=True, serialize=False)),
                ('seuil', models.FloatField()),
            ],
            options={
                'db_table': 'params',
            },
        ),
        migrations.CreateModel(
            name='Creneaux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_creneau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionSoutien.creneau')),
                ('id_param', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Param.paramdef')),
            ],
            options={
                'db_table': 'creneaux',
                'unique_together': {('id_creneau', 'id_param')},
            },
        ),
    ]
