# Generated by Django 3.2.12 on 2023-12-07 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Param', '0002_rename_creneaux_creneaudef_alter_creneaudef_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paramdef',
            name='seuil',
        ),
    ]
