# Generated by Django 3.2.12 on 2024-02-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Param', '0003_remove_paramdef_seuil'),
    ]

    operations = [
        migrations.AddField(
            model_name='paramdef',
            name='profs_mails',
            field=models.CharField(default='', max_length=500),
        ),
    ]
